name: etherscan_api
description: A dart library to access the etherscan.io apis. 
version: 1.0.1
homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^5.5.0+1
  dartz: ^0.10.1
  equatable: ^2.0.0
  logger: ^2.4.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.25.8
